/* BENCH:q1 목록 1페이지 (최신순) - PrdSQL.selectPrdList 의 기본 경로
   보려는 것 : 조인 4개 + 정렬의 기본 비용. 사용자가 가장 많이 보는 화면. */
SELECT
    A.PRD_CD, A.PRD_NM, A.SMPL_DESC, A.PRD_STAT_CD,
    B.SALE_PRC, B.CARD_DISC_PRC, B.CASH_DISC_PRC,
    C.IMG_PATH, D.CAT_NM
FROM TB_PRD_MST A
LEFT JOIN TB_PRD_PRC B ON A.PRD_CD = B.PRD_CD
LEFT JOIN TB_PRD_IMG C ON A.PRD_CD = C.PRD_CD AND C.IMG_TP_CD = '10' AND C.SORT_SEQ = 1
LEFT JOIN TB_CAT_MNG D ON A.L_CAT_CD = D.CAT_CD
WHERE A.PRD_STAT_CD IN ('30', '40', '50')
ORDER BY A.REG_DT DESC
LIMIT {{PAGE_SIZE}} OFFSET 0;
